# Generated by Django 4.1.5 on 2023-01-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_dollar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='new_price',
        ),
    ]
