# Generated by Django 4.1.5 on 2023-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_new_dollar_remove_post_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
